// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxyIE5GH8bTKGJKJ-ZOk1kZbJ4XdMNqc',
    appId: '1:996598872036:web:5aad5a14826c7711ac39f1',
    messagingSenderId: '996598872036',
    projectId: 'dance-b3133',
    authDomain: 'dance-b3133.firebaseapp.com',
    storageBucket: 'dance-b3133.firebasestorage.app',
    measurementId: 'G-XT97PK87RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmLQG25GyHH67hw89_8xOpLrephSYlyNk',
    appId: '1:996598872036:android:a54ab61d74775ae1ac39f1',
    messagingSenderId: '996598872036',
    projectId: 'dance-b3133',
    storageBucket: 'dance-b3133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgDnalhrq7mFX6ra4DoawAYIxDBejB2eM',
    appId: '1:996598872036:ios:09f9dca9708d5d03ac39f1',
    messagingSenderId: '996598872036',
    projectId: 'dance-b3133',
    storageBucket: 'dance-b3133.firebasestorage.app',
    iosBundleId: 'com.example.danceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgDnalhrq7mFX6ra4DoawAYIxDBejB2eM',
    appId: '1:996598872036:ios:09f9dca9708d5d03ac39f1',
    messagingSenderId: '996598872036',
    projectId: 'dance-b3133',
    storageBucket: 'dance-b3133.firebasestorage.app',
    iosBundleId: 'com.example.danceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxyIE5GH8bTKGJKJ-ZOk1kZbJ4XdMNqc',
    appId: '1:996598872036:web:75ecfe0392ec45b0ac39f1',
    messagingSenderId: '996598872036',
    projectId: 'dance-b3133',
    authDomain: 'dance-b3133.firebaseapp.com',
    storageBucket: 'dance-b3133.firebasestorage.app',
    measurementId: 'G-2C093J3Z5B',
  );
}
